language: ruby
script: 'bundle exec rake test:coverage --trace'
install:
  - bundle install --retry=3
rvm:
  - 2.0.0
  - 2.1.0
  - 2.1.1
  - 2.1.2
  - 2.1.3
  - 2.1.4
  - 2.1.5
  - 2.2
  - rbx-2

matrix:
  include:
    - rvm: jruby-head
  allow_failures:
    - rvm: jruby-head
